### ISSUE TITLE
Polygon with vertice in inside

### ISSUE THREAD

**Issue by RealPeha** [piqnt/planck.js#101]
When I wanted to create a polygon of complex shape, I encountered such a problem:
this
```javascript
world.createDynamicBody(Vec2(0.0, 10.0))
    .createFixture(Polygon([
      Vec2(-5, 0),
      Vec2(5, 0),
      Vec2(5, 5),
      Vec2(-5, 5),
    ]))
```
and this
```javascript
world.createDynamicBody(Vec2(0.0, 10.0))
    .createFixture(Polygon([
      Vec2(-5, 0),
      Vec2(5, 0),
      Vec2(5, 5),
      Vec2(0, 3),
      Vec2(-5, 5),
    ]))
```
is the same
The function does not create a polygon with vertices inside it. [I found](https://github.com/shakiba/planck.js/blob/master/example/CharacterCollision.js#L67) that the Chain function can do this, but I was not able to make a dynamic body out of it
Why and how to solve it?

**Comment by zOadT** [comment]
box2d only supports convex shapes and because of that `Polygon` actually creates a shape that corresponds to the convex hull (see [this example](http://piqnt.com/planck.js/ConvexHull)).

But you can nontheless create bodys with a convave shape. You just have to split the shape into convex subparts (e.g. in your case it could be `Polygon([Vec2(-5,0),Vec2(0,0),Vec2(0,3),Vec2(-5,5)])` and `Polygon([Vec2(5,0),Vec2(0,0),Vec2(0,3),Vec2(5,5)])`) and add two fixtures (one for each subpart) to the body.
