### ISSUE TITLE
About world.step acceleration problem

### ISSUE THREAD

**Issue by citizenll** [piqnt/planck.js#150]
I'm using planck.js to make a football game.
I'm confused about the acceleration, I don't know what the problem is. When I render using 30 fps and world.step(delta) is called using delta = 1/30s, it is behaving normally. The actual trajectory of the object matches the trajectory predicted by the formula I used to predict the trajectory from this article
http://www.iforce2d.net/b2dtut/projected-trajectory

The problem is that when I want the object motion to be accelerated, I use world.step(delta*2), and the rendering is still at 30 fps, the object motion is indeed accelerated, the performance is what I want, but there is a problem that the actual motion of the object does not match my predicted path. The force gets smaller like that. Should we actually get the same result using the same force even with different deltas?

(English not good, use translation)

**Comment by shakiba** [comment]
Can you please try `world.step(delta); world.step(delta);`, instead of `world.step(delta * 2);`?

**Comment by SilenceDN** [comment]
> Can you please try `world.step(delta); world.step(delta);`, instead of `world.step(delta * 2);`?

Yes, using world.step(delta); world.step(delta); can get the performance right.
But the reality is that I want to use this acceleration effect on a single object, not on all objects globally.
Before I did that, I tried to modify the source code by adding a property [m_speed] to the body, and then I modified part of the code in Solver.prototype.solveIsland:
```js
 //PI
  var dt = step.dt;
  //PI_END

  Initialize the body state. for (var i = 0; i < this.m_bodies.length; ++i) { // Integrate velocities and apply damping.
  for (var i = 0; i < this.m_bodies.length; ++i) {
    var body = this.m_bodies[i];

    // PI
    var h = dt * (body.m_speed || 1);
    // PI END
  ....
}
```
At first it looks like the effect is achieved, but only after careful observation do I find the problem above. I tested and found that delta*2 and body.m_speed = 2 have the same effect, that's why I came to ask this question. May I ask if this problem is easy to solve? Or what other way to achieve this effect?

**Comment by shakiba** [comment]
As far as I know delta (in `world.step(delta)`) and also h is supposed to be constant for the library to work correctly.

Another option might be to temporary inactivate other objects (`body.setActive(false)`).

**Comment by SilenceDN** [comment]
😀Thank you so much for your reply, it looks like I'll have to spend more time on this issue or compromise!

**Comment by shakiba** [comment]
I'm closing this, please feel free to reopen if needed.
