### ISSUE TITLE
When will version 1 be released?

### ISSUE THREAD

**Issue by quinton-ashley** [piqnt/planck.js#227]
When will version 1 be released? This library has been in a pre-release/alpha status for a long time. It seems like development has stagnated. Are there still plans to release version 1? If not, I think it'd be best to release a version 1.0.0 asap for the benefit of people installing planck with npm or using cdn links.

**Comment by zOadT** [comment]
Good point. There were some more ambitious plans for 1.0 for which we sadly currently don't have the time, so probably a smaller 1.0 release is a good idea. Still wouldn't want to commit on a release time yet, because (also for the smaller scoped release) there are some nasty things to think through before we want to release 1.0

**Comment by shakiba** [comment]
v1-beta is released now, v1 will be released a little bit latter and will be pretty much the same.

**Comment by shakiba** [comment]
Thanks for letting me, I'm glad there was no new issue. I need to finish up some minor testbed updates before v1.

Beta release should work over cdn and npm without any issue, is there any specific issue? If so it is better that we fix them before v1 anyway.

**Comment by quinton-ashley** [comment]
All good! No issues. Looking forward to the release of v1
