### ISSUE TITLE
Raycasts phasing through walls

### ISSUE THREAD

**Issue by codingMASTER398** [piqnt/planck.js#270]
Hello! p5play user here. Although ray-casting isn't officially supported in p5play, there's a simple workaround to access the native APIs.

I've attached a video of the error occurring.
[Screencast from 2024-01-29 16-38-38.webm](https://github.com/piqnt/planck.js/assets/55938439/51c93ad2-67f2-4dec-8725-f8559f4566a2)

I'm doing asynchronous raycasts like this:
```js
function raycast(pos, direction){
    return new Promise((res)=>{
        let rays = [], start = planck.Vec2(pos.x, pos.y), end = planck.Vec2(
            Math.round(pos.x + (10  * Math.cos(direction * Math.PI / 180))),
            Math.round(pos.y + (10  * Math.sin(direction * Math.PI / 180)))
        )
    
        world.rayCast(start, end, (c, c2)=>{ // Raycast is here
            c.intersection = c2
            rays.push(c)
        })
    
        setTimeout(()=>{
            res(rays)
        }, 10)
    })
}
```
Taking in a position of the origin, then doing some maths to figure out a position in the direction I want, casting & waiting 10ms for all the responses.

I then sort them:
```js
rays = rays.sort((a,b)=>{
    return dist(a.intersection.x, a.intersection.y, this.obj.x, this.obj.y)
        - dist(b.intersection.x, b.intersection.y, this.obj.x, this.obj.y)
})
```

and I assume the first element of that array is the closest raycast, however in the video you can see that is not always the case, mostly between certain rotations?

I'm fairly new to this so any advice will be extremely helpful. Sorry I can't provide an in-depth explanation.

**Comment by codingMASTER398** [comment]
I inexplicably solved this using the "RayCastClosest" example at https://piqnt.com/planck.js/RayCast .
I just imported the function, and everything seemed to... magically work? No idea what wizardry it does. More helpful documentation on this would be nice.

**Comment by shakiba** [comment]
What function did you import that solved the problem?

**Comment by quinton-ashley** [comment]
@shakiba In the docs, the use of the term "callback" in `WorldRayCastCallback` is a bit misleading because planck's `world.rayCast` is not an async function. "callback" in JavaScript refers to an input function that runs after the called function finishes, almost always because the caller function is async. I think this function could more accurately be called a filter.

https://github.com/piqnt/planck.js/blob/master/docs/api/classes/world.md#raycast

Also I think since codingMASTER was only interested in finding the closest callback so he found the solution to that in the `RayCastClosest` function.

@codingMASTER398 This may have been added by Shakiba later but the example now notes "do not assume that fixtures are reported in order. However, by clipping, we can always get the closest fixture."

Why is that? It's because the ray cast is not performed in the straight forward way one may expect, by testing points along the ray cast line, which is called [Ray Marching](https://en.wikipedia.org/wiki/Ray_marching).

Ray casting in Box2D is done by looking at nearby fixtures in the Dynamic AABB Tree, a specialized data structure that stores all the fixture's AABBs. The visually closest nodes to the fixture at the starting point may be stored further apart in the dynamic tree. Since planck's raycasting actually works by looping through fixtures in the tree, that's why fixtures may not be reported in order. Complicated stuff aye?

This also means that unlike with ray marching, we can't cancel a planck raycast just because for example it hits a wall, because the wall might be behind a target object.

**Comment by quinton-ashley** [comment]
In the filter function, returning:

 -1 stops the ray casting
 >0 limits the ray to not go beyond that fixture
 1 maintains the full length of the ray cast

**Comment by shakiba** [comment]
@quinton-ashley thanks for your comments and suggestions.

To clarify, the return value of the callback is used to update the initial [`maxFraction`](https://www.iforce2d.net/b2dtut/raycasting) in the raycast input. So 0 would effectively stops the raycast, and negative is ignored as invalid.

Also, I think the parameter is named correctly according to [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Callback_function):

>A callback function is a function passed into another function as an argument, which is then invoked inside the outer function to complete some kind of routine or action.

>Examples of synchronous callbacks include the callbacks passed to [Array.prototype.map()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [Array.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), etc. Examples of asynchronous callbacks include the callbacks passed to [setTimeout()](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) and [Promise.prototype.then()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then).

**Comment by quinton-ashley** [comment]
@shakiba you are right! hmm I didn't know those kinds of functions were also called callbacks.
